### ISSUE TITLE
No modules with partial data in `nonmpi_partial_modules.darshan`

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan-logs#16]
[`nonmpi_partial_modules.darshan`](https://github.com/darshan-hpc/darshan-logs/tree/main/darshan_logs/nonmpi_partial_modules) is supposed to contain modules with partial data, but there doesn't seem to be any hard evidence of this. For example, the following commands don't yield any results: 
- `darshan-parser nonmpi_partial_modules.darshan | grep incomplete` 
- `darshan-dxt-parser nonmpi_partial_modules.darshan | grep incomplete`

The expected output for the above commands using a log with partial module data is something like the following:
```
# *ERROR*: The MOD_NAME module contains incomplete data!
#            This happens when a module runs out of
#            memory to store new record data.

# To avoid this error, consult the darshan-runtime
# documentation and consider setting the
# DARSHAN_EXCLUDE_DIRS environment variable to prevent
# Darshan from instrumenting unecessary files.

# You can display the (incomplete) data that is
# present in this log using the --show-incomplete
# option to darshan-parser.
```

Additionally, generating the darshan summary report for this log yields the following table:

![Screen Shot 2022-01-24 at 3 46 22 PM](https://user-images.githubusercontent.com/46797896/150877782-d51ebf2e-c965-46de-8f25-b55b6861c690.png)

If this is confirmation enough I think the following need to be updated: 
- README
- ~log's directory name~
- ~log file name~
- ~any tests in the main repo that use it by the original name~

**Comment by tylerjereddy** [comment]
I'd actually suggest just changing the logs repo README to clarify, but not any of the other disruptions. Making assumptions about the meaning of things like "good" and "bad" in log names is also confusing, but probably not worth renaming them at this point.

Indeed, Shane may have meant a different meaning for "partial" anyway, so could just clarify that eventually. And, of course, worth pointing out that it is always good to carefully check any claims about log properites *before* PRs get merged to the logs repo (even if someone created the log themselves).

**Comment by nawtrey** [comment]
Okay, that's a fair point. I've updated the issue comment.

**Comment by carns** [comment]
I think there was some confusion re: the significance of this log when it was added to the repo (and also we didn't vet it properly before merging).

I would push back and vote for updating readme and renaming file/dir too.  A sensible file/dir name is helpful for ad-hoc use and the commit noise isn't a problem in this context.

I'm happy to open a PR making these corrections (I'm the one that fumbled the PR review for one thing!), but first let me confirm why it was notable from the pydarshan perspective so I can comment on that in the readme.

If I understand correctly, It looks like the original issue had to do with whether or not the IO time was visible in the bar graph for average I/O cost.  @nawtrey can you confirm what that looks like now in the current pydarshan tools?  I don't know if we ended up at a point where it's now visible with our current calculation method, or if the calculation method is correct but it still doesn't show up just because the I/O time is so low.  Either is interesting; I just want to note the expectation.

More generally the properties of the log are that it is non-mpi, has dxt enabled, and is anonymized.

**Comment by tylerjereddy** [comment]
This stuff was all dealt with in the main repo with issues/PRs/bug fixes enabled by the addition of the new log. If you want to proceed with opening the PRs to change the name/paths here and in the main repo fair enough.

Interestingly, you may not be able to accomplish that without merging a PR with failing CI, because both projects pull each other in so there's a difficult-to-avoid chicken and egg problem. If you change the name of the file in the main repo, it won't be able to find the log until the update happens here. If you change the name of the file here, the main repo tests won't be able to find the file when the CI runs here.

While the disruption isn't that large, we do have quite a few deceptively/ambiguously-named logs.

**Comment by carns** [comment]
> This stuff was all dealt with in the main repo with issues/PRs/bug fixes enabled by the addition of the new log. If you want to proceed with opening the PRs to change the name/paths here and in the main repo fair enough.

Ok, great.  In the readme we can just note generally that it has a relatively small percentage of runtime spent in I/O rather than naming a specific expectation from the python summary.

> 
> Interestingly, you may not be able to accomplish that without merging a PR with failing CI, because both projects pull each other in so there's a difficult-to-avoid chicken and egg problem. If you change the name of the file in the main repo, it won't be able to find the log until the update happens here. If you change the name of the file here, the main repo tests won't be able to find the file when the CI runs here.

Ah Ok.  I didn't think of that but it should be easy to fix.

> While the disruption isn't that large, we do have quite a few deceptively/ambiguously-named logs.

I'm sure that's true.  I'm just being picky about this one because it isn't just ambiguous, its overtly incorrect.
